### ISSUE TITLE
Score Capitol Letters Higher in Fuzzy Search

### ISSUE THREAD

**Issue by steveoh** [atom/fuzzaldrin#21]
It seems that Sublime and possibly the chrome dev tools give a higher priority to capitol letters when searching. This makes finding the file `MyFileName.ext` much easier since you can type `MFN` and not be bothered with having to spell it out. I think this is a great productivity feature since you can type less letters which introduces less spelling errors.

For instance, assume a list of files that would represent a front end javascript usecase.

``` js
var files = ['FilterFactors.js', 
'FilterFactors.styl', 
'FilterFactors.html', 
'FilterFactorTests.html', 
'SpecFilterFactors.js'];
```

In sublime, I could type `FFT` to get to **F**ilter**F**actor**T**ests.html. In atom, `FFT` matches **F**ilter**F**ac**t**ors .js, .styl, and .html above FilterFactorTests.html.

**Comment by jeancroy** [comment]
PR #22 now cover this case
