### ISSUE TITLE
Question: Is this package already used in Atom?

### ISSUE THREAD

**Issue by janmarek** [atom/fuzzaldrin#26]
I don't know if I should report situations where Atom could do better with sorting :)

If no, is there a way how to "turn it on"?

**Comment by plrenaudin** [comment]
There is already a PR #22 which improves a lot the pertinence of the results.
Unfortunately it's not merged yet.

**Comment by mnquintana** [comment]
Atom does already use fuzzaldrin for fuzzy searching, and there are [quite](https://github.com/atom/fuzzaldrin/issues/23) [a](https://github.com/atom/fuzzaldrin/issues/21) [few](https://github.com/atom/fuzzaldrin/issues/20) [open](https://github.com/atom/fuzzaldrin/issues/18) [issues](https://github.com/atom/fuzzaldrin/issues/17) for improving the algorithm, so I'm going to close this out.
