### ISSUE TITLE
Can I disable sorting?

### ISSUE THREAD

**Issue by EvilClosetMonkey** [atom/fuzzaldrin#31]
Is it possible to disable the sorting of results?

I have a use for fuzzaldrin in which the sorting is not beneficial, but the matching is. Currently I run a set of sorted candidates through the filter and then have to resort them -- not horrible, but still an extra step that would be nice not to do.

I do use both filtering and sorting in other cases. I'd like to use the same fuzzysearch library across all filtering instances.

**Comment by jeancroy** [comment]
Just looked at source code and both seems tied together.

This project basically does what you want, it's a small snippet but also from a well established maintainer.
https://github.com/bevacqua/fuzzysearch/blob/master/index.js

**Comment by EvilClosetMonkey** [comment]
Thanks @jeancroy.
